name: untitled
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^5.0.0+2
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  toast: ^0.2.9
  cloud_firestore: ^3.4.9
  google_sign_in: ^5.4.2
  firebase_auth: ^3.10.0
  url_launcher: ^6.1.5
  location: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
